@startuml kalastus
left to right direction

entity admin {
  +id : int <<PK>>
  username : string
  pword : string
}

entity viikonlounasRuokamenu {
  +id : int <<PK>>
  paiva : string
  ruoka : string
  paivamaara : datetime
  juomat : string
}

entity ruokamenu {
  +id : int <<PK>>
  ruokalaji : string
  ruoka : string
  ainekset: string
  hinta : int
}

entity juomat {
  +id : int <<PK>>
  juoma : string
  hinta: int
  tyyppi: string
}
 
entity aukioloajat {
  +id : int <<PK>>
  paiva : string
  kellonaika : datetime
  paivamaara : datetime
}
 
@enduml