@startuml kalastus
left to right direction

entity admin {
  +id : int <<PK>>
  username : string <<UNIQUE>>
  pword : string
}

entity viikonlounasRuokamenu {
  +id : int <<PK>>
  paiva : string
  ruoka : string
  paivamaara : datetime
  juomat : string
}

entity ruokamenu {
  +id : int <<PK>>
  ruokalaji : string
  ruoka : string
  ainekset: text
  hinta : decimal(6,2)
}

entity juomat {
  +id : int <<PK>>
  juoma : string
  hinta: decimal(6,2)
  tyyppi: string
}
 
entity aukioloajat {
  +id : int <<PK>>
  paiva : string
  kellonaika : string
  paivamaara : date
}
 
@enduml